/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppRequestsRouteImport } from './routes/app.requests'
import { Route as AppSearchRouteImport } from './routes/app.search'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppChatIdRouteImport } from './routes/app.chat.$id'
import { Route as AppGroupNewRouteImport } from './routes/app.group.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRequestsRoute = AppRequestsRouteImport.update({
  id: '/app/requests',
  path: '/app/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/app/search',
  path: '/app/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/app/settings',
  path: '/app/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AppChatIdRoute = AppChatIdRouteImport.update({
  id: '/app/chat/$id',
  path: '/app/chat/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppGroupNewRoute = AppGroupNewRouteImport.update({
  id: '/app/group/new',
  path: '/app/group/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/requests': typeof AppRequestsRoute
  '/app/search': typeof AppSearchRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/app/chat/$id': typeof AppChatIdRoute
  '/app/group/new': typeof AppGroupNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/requests': typeof AppRequestsRoute
  '/app/search': typeof AppSearchRoute
  '/app/settings': typeof AppSettingsRoute
  '/app': typeof AppIndexRoute
  '/app/chat/$id': typeof AppChatIdRoute
  '/app/group/new': typeof AppGroupNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/requests': typeof AppRequestsRoute
  '/app/search': typeof AppSearchRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/app/chat/$id': typeof AppChatIdRoute
  '/app/group/new': typeof AppGroupNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/app/requests'
    | '/app/search'
    | '/app/settings'
    | '/app/'
    | '/app/chat/$id'
    | '/app/group/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/requests'
    | '/app/search'
    | '/app/settings'
    | '/app'
    | '/app/chat/$id'
    | '/app/group/new'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/app/requests'
    | '/app/search'
    | '/app/settings'
    | '/app/'
    | '/app/chat/$id'
    | '/app/group/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  AppRequestsRoute: typeof AppRequestsRoute
  AppSearchRoute: typeof AppSearchRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppChatIdRoute: typeof AppChatIdRoute
  AppGroupNewRoute: typeof AppGroupNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/requests': {
      id: '/app/requests'
      path: '/app/requests'
      fullPath: '/app/requests'
      preLoaderRoute: typeof AppRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/search': {
      id: '/app/search'
      path: '/app/search'
      fullPath: '/app/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/app/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/chat/$id': {
      id: '/app/chat/$id'
      path: '/app/chat/$id'
      fullPath: '/app/chat/$id'
      preLoaderRoute: typeof AppChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/group/new': {
      id: '/app/group/new'
      path: '/app/group/new'
      fullPath: '/app/group/new'
      preLoaderRoute: typeof AppGroupNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  AppRequestsRoute: AppRequestsRoute,
  AppSearchRoute: AppSearchRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppChatIdRoute: AppChatIdRoute,
  AppGroupNewRoute: AppGroupNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
